name: 'demo_datawarehouse'
version: '1.0.0'
config-version: 2

profile: 'demo'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  demo_datawarehouse:
    staging:
      +materialized: view
    marts:
      +materialized: table

seeds:
  demo_datawarehouse:
    +schema: seeds
